<?php

namespace TMD\ProdBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EcommCmdepRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EcommCmdepRepository extends EntityRepository
{
    public function findArticlesByFile($files)
    {
        return $this

            ->createQueryBuilder('cmd')
            ->innerJoin('cmd.numbl', 'ligne')
            ->where('ligne.idfile IN (:id)')
            ->setParameter('id', $files)
            ->select('ligne.idfile')
            ->addSelect('sum(cmd.quantite) as quantite')
            ->addSelect('cmd.libelle')
            ->addSelect('cmd.flagart')
            ->groupBy('ligne.idfile, cmd.libelle')
            ->getQuery()
            ->getResult()

            ;
    }

    public function findArticlesByBlforSynthese($bl)
    {
        return $this
            ->createQueryBuilder('cmd')
            ->innerJoin('cmd.numbl', 'ligne')
            ->where('cmd.numbl IN (:id)')
            ->setParameter('id', $bl)
            ->select('ligne.idfile')
            ->addSelect('sum(cmd.quantite) as quantite')
            ->addSelect('cmd.libelle')
            ->addSelect('cmd.flagart')
            ->groupBy('cmd.libelle')
            ->getQuery()
            ->getResult()

            ;
    }

    public function findArticlesByFileArray($files)
    {
        return $this
            ->createQueryBuilder('cmd')
            ->innerJoin('cmd.numbl', 'ligne')
            ->where('ligne.idfile IN (:id)')
            ->setParameter('id', $files)
            ->select('ligne.idfile')
            ->addSelect('sum(cmd.quantite) as quantite')
            ->addSelect('cmd.libelle')
            ->addSelect('cmd.flagart')
            ->groupBy('ligne.idfile, cmd.libelle')
            ->getQuery()
            ->getArrayResult()
            ;
    }

    public function findArticlesPersoByFileArray($files)
    {
        return $this
            ->createQueryBuilder('cmd')
            ->innerJoin('cmd.numbl', 'ligne')
            ->where('ligne.idfile IN (:id)')
            ->setParameter('id', $files)
            ->andWhere('cmd.flagart = 0')
            ->select('ligne.idfile')
            ->select('ligne.idfile')
            ->addSelect('cmd.libelle')
            ->addSelect('ligne.numbl')
            ->addSelect('count(cmd.perso1)')
            ->addSelect('cmd.flagart')
            ->addSelect('cmd.perso1')
            ->addSelect('cmd.perso2')
            ->orderBy('cmd.perso1', 'ASC')
            ->groupBy('cmd.perso1')
            ->getQuery()
            ->getArrayResult()
            ;
    }



    public function findArticlesReclaByFile($files)
    {
        return $this
            ->createQueryBuilder('cmd')
            ->innerJoin('cmd.numbl', 'ligne')
            ->where('ligne.idfile IN (:id)')
            ->setParameter('id', $files)
            ->andWhere('cmd.libelle LIKE :rec')
            ->setParameter('rec', '%cla%' )
            ->select('count(DISTINCT(ligne.numbl)) AS q' )
            ->addSelect('ligne.idfile')
            ->groupBy('ligne.idfile')
            ->getQuery()
            ->getResult()

            ;
    }


    public function findArticlesByOpe($files)
    {
        return $this
            ->createQueryBuilder('cmd')
            ->innerJoin('cmd.numbl', 'ligne')
            ->where('ligne.idfile IN (:id)')
            ->setParameter('id', $files)
            ->select('sum(cmd.quantite) as quantite')
            ->addSelect('cmd.libelle')
            ->addSelect('cmd.flagart')
            ->addSelect('cmd.codearticle')
            ->groupBy('cmd.libelle')
            ->orderBy('quantite', 'DESC')
            ->getQuery()
            ->getArrayResult()

            ;
    }



    public function findArticlesByBL($numBL)
    {
        return $this
            ->createQueryBuilder('cmd')
            ->innerJoin('cmd.numbl', 'ligne')
            ->where('cmd.numbl IN (:id)')
            ->setParameter('id', $numBL)
            ->andWhere('cmd.flagart = (:f)')
            ->setParameter('f', 0)
            ->select('cmd.perso1')
            ->addSelect('sum(cmd.quantite) as qte')
            ->addSelect('cmd.libelle')
            ->addSelect('ligne.numbl')
            ->groupBy('cmd.perso1, cmd.libelle, cmd.numbl')
            ->getQuery()
            ->getResult()

            ;
    }

    public function findArticlesByFileBl($numBL)
    {
        return $this
            ->createQueryBuilder('cmd')
            ->innerJoin('cmd.numbl', 'ligne')
            ->where('ligne.numbl IN (:id)')
            ->setParameter('id', $numBL)
            ->select('sum(cmd.quantite) as quantite')
            ->addSelect('cmd.libelle')
            ->addSelect('cmd.flagart')
            ->addSelect('ligne.numbl')
            ->groupBy('cmd.libelle, ligne.numbl')
            ->getQuery()
            ->getArrayResult()

            ;
    }


}
