<?php

namespace TMD\ProdBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EcommFilesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EcommFilesRepository extends EntityRepository
{
    public function fileByOperation($idOpe)
    {
        return $this
            ->createQueryBuilder('f')
            ->where('f.idappli = :id')
            ->setParameter('id', $idOpe)
            ->getQuery()
            ->getResult()
            ;
    }

    public function idfileByOperation($idOpe)
    {
        return $this
            ->createQueryBuilder('f')
            ->where('f.idappli = :id')
            ->setParameter('id', $idOpe)
            ->select('f.idfile')
            ->getQuery()
            ->getResult()
            ;
    }




}
