<?php

namespace TMD\ProdBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EcommStatutRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EcommStatutRepository extends EntityRepository
{

    public function getByAbrege ( string $abrege ) {
        return $this->findOneBy(["abregestatut" => $abrege]);
    }

}
