<?php

namespace TMD\ProdBundle\Repository;

/**
 * InputDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InputDataRepository extends \Doctrine\ORM\EntityRepository
{
}
