<?php

namespace TMD\ProdBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ViewBlAppRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ViewBlAppRepository extends EntityRepository
{
//    public function findAllFileByOpeAndProd($idOpe)
//    {
//        return $this
//            ->createQueryBuilder('b')
//            ->where('b.idappli = :id')
//            ->setParameter('id', $idOpe)
//            ->andwhere('b.dateProduction != :dat')
//            ->setParameter('dat', '0000-00-00 00:00:00')
//            ->addSelect('count(b.bl) AS BlProd')
//            ->groupBy('b.idfile')
//            ->getQuery()
//            ->getResult()
//            ;
//    }
//
//    public function findAllFileByOpe($idOpe)
//    {
//        return $this
//            ->createQueryBuilder('b')
//            ->where('b.idappli = :id')
//            ->setParameter('id', $idOpe)
//            ->getQuery()
//            ->getResult()
//            ;
//    }
//
//    public function findNbBlByop($idOpe)
//    {
//        return $this
//            ->createQueryBuilder('b')
//            ->where('b.idappli = :id')
//            ->setParameter('id', $idOpe)
//            ->select('count(b.idbl) AS nbTotBl')
//            ->getQuery()
//            ->getResult()
//            ;
//    }

    public function findAllBlByFileNonProd($idfile)
    {
        return $this
            ->createQueryBuilder('b')
            ->where('b.idfile = :id')
            ->setParameter('id', $idfile)
            ->andwhere('b.dateProduction = :date')
            ->setParameter('date', '0000-00-00 00:00:00')
            ->getQuery()
            ->getResult()
            ;
    }


//    public function findNbBlByFile($idFile)
//    {
//        return $this
//            ->createQueryBuilder('b')
//            ->where('b.idfile = :id')
//            ->setParameter('id', $idFile)
//            ->select('count(b.idbl) AS nbBl')
//            ->getQuery()
//            ->getResult()
//            ;
//    }

}
