tmd_core_homepage:
    path:     /
    defaults: { _controller: TMDCoreBundle:Core:index }

tmd_core_productionJour:
    path: /prodDuJour
    defaults:
        _controller: TMDCoreBundle:Core:prodJour
    methods: [POST]

tmd_core_productionVeille:
    path: /prodVeille
    defaults:
        _controller: TMDCoreBundle:Core:prodVeille
    methods: [POST]

tmd_core_donneResteProd:
    path: /ResteProd
    defaults:
        _controller: TMDCoreBundle:Core:resteProd
    methods: [POST]

tmd_core_erreurWS:
    path: /erreurWS
    defaults:
        _controller: TMDCoreBundle:Core:erreurWS
    methods: [POST]

tmd_core_rectificationWS:
    path: /rectificationWS/{idOpe}/{current}
    defaults:
        _controller: TMDCoreBundle:Core:rectificationWS
        idOpe: 0
        current: 0

tmd_core_impressionSearch:
    path: /reimpressionEtikt/
    defaults:
        _controller: TMDCoreBundle:Core:impressionSearch

tmd_core_reimpressionEtikt:
    path: /reimpressionEtikt/imprim
    defaults:
        _controller: TMDCoreBundle:Core:reimpressionEtikt
    methods: [POST]

tmd_prod_transports:
    path: /transport
    defaults:
        _controller: TMDCoreBundle:Core:transports


tmd_core_transportForm:
    path: /transportForm
    defaults:
        _controller: TMDCoreBundle:Core:transportForm

tmd_core_transportFormSuite:
    path: /transportFormSuite
    defaults:
        _controller: TMDCoreBundle:Core:transportFormSuite

tmd_core_savetarifTr:
    path: /saveTarif/
    defaults:
        _controller: TMDCoreBundle:Core:savetarifTr

tmd_core_searchTransport:
    path: /searchTransport
    defaults:
        _controller: TMDCoreBundle:Core:searchTransport

tmd_core_saveTransportMasse:
    path: /saveTarifMasse
    defaults:
        _controller: TMDCoreBundle:Core:saveTransportMasse

tmd_core_searchClients:
    path: /searchClients
    defaults:
        _controller: TMDCoreBundle:Core:searchClients

tmd_core_saveTarifClient:
    path: /saveTarifClient
    defaults:
        _controller: TMDCoreBundle:Core:saveTarifClient