<?php

namespace TMD\AppliBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EcommTransportReposito
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EcommTransportRepository extends EntityRepository
{
    public function findallTransport()
    {
        return $this
            ->createQueryBuilder('n')
            ->innerJoin('n.idtransporteur', 'tr')
            ->addSelect('tr.idtransporteur')
            ->addSelect('tr.libelletransporteur')
            ->addSelect('n.codetransport')
            ->addSelect('n.libelletransport')
            ->getQuery()
            ->getArrayResult()

            ;
    }

    public function findByTransporteur($idTransporteur){
        return $this
            ->createQueryBuilder('t')
            ->innerJoin('t.idtransporteur', 'tr')
            ->where('tr.idtransporteur IN (:idtransporteur)')
            ->setParameter('idtransporteur', $idTransporteur)
            ->getQuery()
            ->getArrayResult();
    }
}
