<?php

namespace TMD\AppliBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EcommTransportReposito
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EcommCompteRepository extends EntityRepository
{
    public function findallCompte()
    {
        return $this
            ->createQueryBuilder('n')
            ->innerJoin('n.idclient', 'client')
            ->addSelect('client.idclient')
            ->getQuery()
            ->getArrayResult()
            ;
    }
}
