<?php

namespace TMD\DpdBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrackingsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TrackingsRepository extends EntityRepository
{
    public function findStatutByBL($numBl)
    {

        $query = $this->_em->createQuery('SELECT tr.numbl, st.libelle, tr.dateStatut FROM TMDDpdBundle:Trackings tr INNER JOIN TMDDpdBundle:Colisstatut st WITH tr.statut = st.statut WHERE tr.numbl IN ('.implode(",",$numBl).')');
        $results = $query->getArrayResult();
        return $results;
        ;
    }

}
