<?php

namespace TMD\MinosBundle\Repository;

/**
 * OracleTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OracleTRepository extends \Doctrine\ORM\EntityRepository
{
}
