tmd_zpl_homepage:
    path:     /etiquettes
    defaults: { _controller: TMDZplBundle:Default:index }

tmd_zpl_imprimEtiq:
    path:     /printZpl
    defaults: { _controller: TMDZplBundle:Default:imprimEtiq }

tmd_zpl_imprimColissimoBordereau:
    path:     /printBordereauCol
    defaults: { _controller: TMDZplBundle:Default:imprimColissimoBordereau }

tmd_zpl_imprimColissimoInformation:
    path:     /printInfoBordereauCol
    defaults: { _controller: TMDZplBundle:Default:imprimColissimoInformation }
