<?php

namespace TMD\ColisPriveBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrackingsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TrackingsRepository extends EntityRepository
{


    public function findStatutByBL($numBl)
    {

            $query = $this->_em->createQuery('SELECT tr.numbl, st.libelle, tr.dateStatut FROM TMDColisPriveBundle:Trackings tr INNER JOIN TMDColisPriveBundle:Colisstatut st WITH tr.statut = st.statut WHERE tr.numbl IN ('.implode(",",$numBl).')');
            $results = $query->getArrayResult();
            return $results;
            ;
    }
    public function findStatutByNumligne($numligne)
    {

        $query = $this->_em->createQuery('SELECT tr.numligne, st.libelle FROM TMDColisPriveBundle:Trackings tr INNER JOIN TMDColisPriveBundle:Colisstatut st WITH tr.statut = st.statut WHERE tr.numligne ='.$numligne);
        $results = $query->getResult();
        return $results;
        ;
    }
}
