tmd_config_homepage:
    path:     /
    defaults: { _controller: TMDConfigBundle:Gestion:index }

tmd_config_addnews:
    path:     /addnew
    defaults:
        _controller: TMDConfigBundle:Gestion:addnew

tmd_config_gestioncmd:
    path: /gestioncmd/client/
    defaults:
        _controller: TMDConfigBundle:Gestion:gestioncmd

tmd_config_gestioncmdClient:
    path: /gestioncmd/client/{idClient}
    defaults:
        _controller: TMDConfigBundle:Gestion:gestioncmdClient

tmd_config_editTracking:
    path: /tracking/{id}
    defaults:
        _controller: TMDConfigBundle:Gestion:editTracking
