services:
#    tmd_config.example:
#        class: TMD\ConfigBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#TMD\ConfigBundle\Controller\GestionController:
#  autowire: true # or define your controller constructor and configure its arguments explicitly
#  tags: ['controller.service_arguments']