tmd_prod_homepage:
    path:     /
    defaults: { _controller: TMDProdBundle:Prod:index }

tmd_prod_client:
    path:     /client/{page}/{nbFichierPage}/{idClient}/{idOpe}
    defaults:
        _controller: TMDProdBundle:Prod:viewClient
        page: 1
        nbFichierPage: 20
        idClient: 0
        idOpe:    0
    requirements:
        page: \d*

tmd_prod_suiviCourant:
    path:     /suiviOpeCourant/{page}/{nbFichierPage}/{idClient}/{idOpe}/{blR}
    defaults:
        _controller: TMDProdBundle:Prod:viewSuiviCourant
        page: 1
        nbFichierPage: 20
        idClient: 0
        idOpe:    0
        blR:      0
    requirements:
        page: \d*

tmd_prod_donneBlNonProd:
    path: /blNonProd
    defaults:
        _controller: TMDProdBundle:Prod:donneBlNonProd
    methods: [POST]

tmd_prod_donneRuptureByFile:
    path: /rupturebyFile
    defaults:
        _controller: TMDProdBundle:Prod:donneRuptureByFile
    methods: [POST]

tmd_prod_donneDepotNull:
    path: /depotNull
    defaults:
        _controller: TMDProdBundle:Prod:donneDepotNull
    methods: [POST]

tmd_prod_calendar:
    path: /calendar
    defaults:
        _controller: TMDProdBundle:Prod:calendar
    methods: [GET]

tmd_prod_calendarDepot:
    path: /calendarDepot
    defaults:
        _controller: TMDProdBundle:Prod:calendarDepot
    methods: [GET]

tmd_prod_donneTrackingsByFile:
    path: /trackingsByFile
    defaults:
        _controller: TMDProdBundle:Prod:donneTrackingsByFile
    methods: [POST]

tmd_prod_annuleTracking:
    path: /annuleTracking
    defaults:
        _controller: TMDProdBundle:Prod:annuleTracking
    methods: [POST]


tmd_prod_exportTrackings:
    path: /rTracking/{idFile}/{prod}
    defaults:
        _controller: TMDProdBundle:Prod:exportTrackingExcel

tmd_prod_exportTrackingsArticles:
    path: /rTrackingArticle/{idFile}/{prod}
    defaults:
        _controller: TMDProdBundle:Prod:exportTrackingArticleExcel

tmd_prod_exportResteProd:
    path: /resteProd/{idoperation}
    defaults:
        _controller: TMDProdBundle:Prod:exportResteProdExcel

tmd_prod_exportarticleRupture:
    path: /ruptureProd/{idoperation}
    defaults:
        _controller: TMDProdBundle:Prod:exportRuptureProdExcel

tmd_prod_exportTrackingExcelbyBL:
    path: /rTrackingBL/{idBLs}/{code}
    defaults:
        _controller: TMDProdBundle:Prod:exportTrackingExcelbyBL

tmd_prod_exportTrackingExcelbyDate:
    path: /rTrackingDate/{date}/{appli}
    defaults:
        _controller: TMDProdBundle:Prod:exportTrackingExcelbyDate

tmd_prod_exportTrackingExcelbyBLArticle:
    path: /rTrackingBLArticle/{date}/{appli}
    defaults:
        _controller: TMDProdBundle:Prod:exportTrackingExcelbyBLArticle

tmd_prod_exportTrackingPresse:
    path: /rTrackingPresse/{date}/{appli}
    defaults:
        _controller: TMDProdBundle:Prod:exportTrackingPresse

tmd_prod_donneTrackingsByDateProd:
    path: /rTrackingDate
    defaults:
        _controller: TMDProdBundle:Prod:exportTrackingbyDate

tmd_prod_donneTrackingsByDateDepot:
    path: /rTrackingDateDepot
    defaults:
        _controller: TMDProdBundle:Prod:exportTrackingbyDateDepot

tmd_prod_donneSyntheseByDateProd:
    path: /syntheseDate
    defaults:
        _controller: TMDProdBundle:Prod:exportSynthesebyDate

tmd_prod_donneSyntheseByDateDepot:
    path: /syntheseDateDepot
    defaults:
        _controller: TMDProdBundle:Prod:exportSynthesebyDateDepot

tmd_prod_rechercheCmd:
    path: /rechercheCmd
    defaults:
        _controller: TMDProdBundle:Prod:rechercheByCmd

tmd_prod_rechercheCodeArticle:
    path: /rechercheCodeArticle
    defaults:
        _controller: TMDProdBundle:Prod:rechercheByCodeArticle

tmd_prod_rechercheModif:
    path: /rechercheModif
    defaults:
        _controller: TMDProdBundle:Prod:rechercheModif

tmd_prod_donneArticleByBl:
    path: /articleByBl
    defaults:
        _controller: TMDProdBundle:Prod:articleByBl

tmd_prod_modifDateDepot:
    path: /modifDateDepot
    defaults:
        _controller: TMDProdBundle:Prod:modifDateDepot

tmd_prod_modifDateProduction:
    path: /modifDateProduction
    defaults:
        _controller: TMDProdBundle:Prod:modifDateProduction

tmd_prod_syntheseArtCoke:
    path: /syntheseArtCoke/{date}
    defaults:
        _controller: TMDProdBundle:Prod:syntheseCoke

tmd_prod_syntheseCoriolis:
    path: /syntheseCoriolis/{date}
    defaults:
        _controller: TMDProdBundle:Prod:syntheseCoriolis

tmd_prod_addApplication:
    path: /addApplication
    defaults:
        _controller: TMDProdBundle:Prod:addApplication

tmd_prod_modifDateDepotProdTraccking:
    path: /modifDateProductionDepotTracking
    defaults:
        _controller: TMDProdBundle:Prod:modifDateProductionDepotTracking

tmd_prod_modifDateDepotProd:
    path: /modifDateProductionDepot
    defaults:
        _controller: TMDProdBundle:Prod:modifDateProductionDepot

tmd_prod_suppNameOperation:
    path: /suppNameOperation
    defaults:
        _controller: TMDProdBundle:Prod:suppNameOperation

tmd_prod_donneTransport:
    path: /donneAllTransport
    defaults:
        _controller: TMDProdBundle:Prod:donneAllTransport


tmd_prod_saisiePnd :
    path: /saisiePnd
    defaults:
        _controller: TMDProdBundle:Pnd:saisiePnd

tmd_prod_pnd:
    path:     /pnd/{idClient}/{idOpe}
    defaults:
        _controller: TMDProdBundle:Pnd:extract
        message:  ''

tmd_prod_pnd_download:
    path:     /pnd/{idClient}/{idOpe}/download
    defaults:
        _controller: TMDProdBundle:Pnd:download

tmd_prod_pnd_save:
    path:     /pnd/{idClient}/{idOpe}/save
    defaults:
        _controller: TMDProdBundle:Pnd:save

tmd_prod_rechercheRupt:
    path: /RechercheRupture
    defaults:
        _controller: TMDProdBundle:Prod:SearchRupt

tmd_prod_annulTrackingAll:
    path: /annulTrackingAll
    defaults:
        _controller: TMDProdBundle:Prod:AnnulTrackingAll

tmd_prod_donneSyntheseBlByDateProd:
    path: /SyntheseBlByDateProd
    defaults:
        _controller: TMDProdBundle:Prod:SyntheseBlByDateProd

tmd_prod_pdf:
    path: /pdftest/{idClient}/{idOpe}/{thisdate}
    defaults:
        _controller: TMDProdBundle:Prod:generate_pdf

tmd_prod_prefacturation:
    path: /prefacturation/{idClient}/{idOpe}/{choix}
    defaults:
        _controller: TMDProdBundle:Prod:Prefacturation

tmd_prod_annuleArticle:
    path: /AnnulArticle
    defaults:
        _controller: TMDProdBundle:Prod:AnnulArticle

